### PR TITLE
fix: mergePaths should not merge paths with styles that depend on bounding box

### LINKED ISSUE #1267: Combining multiple shapes into a <path> breaks <linearGradient>
svgo combines multiple shapes sharing the same `<linearGradient>` into a single `<path>`. This happens in the `mergePaths` plugin, and visually changes the result since the gradient stops are relative to the bounding box of the shape to which the gradient is applied (with the default `gradientUnits="objectBoundingBox"`).

### Input

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 100">
    <linearGradient id="gradient">
        <stop offset="0" stop-color="#ff0000" />
        <stop offset="1" stop-color="#0000ff" />
    </linearGradient>
    <path fill="url(#gradient)" d="M 0 0 H 100 V 100 H 0 z" />
    <path fill="url(#gradient)" d="M 200 0 H 300 V 100 H 200 z" />
</svg>
```

in

### Output

(Indentation restored for clarity.)

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 100">
    <linearGradient id="a">
        <stop offset="0" stop-color="red"/>
        <stop offset="1" stop-color="#00f"/>
    </linearGradient>
    <path fill="url(#a)" d="M0 0h100v100H0zM200 0h100v100H200z"/>
</svg>
```

out

### PR DESCRIPTION
**Pull request by johnkenny54**
This PR fixes the problem raised in issue #1267. The general issue is that merging paths into a single element changes the bounding box, so any style that depends on the bounding box of the element may change behavior. This PR disables merging for any paths that have:

- A fill, filter, or stroke that references a URL.
- A clip-path or mask.

It's possible that there are other scenarios where merging should be disabled, but those above are the only ones that I was able to construct a test case for so far.

With the current regression settings, there is no change in pixel mismatches in the regressions. With the Oxygen files, only one file seems to be affected - scalable/status/weather-few-clouds-night.svg. The clouds were rendered incorrectly in the optimized version before the fix.

Closes #1267

### CODE REVIEW

File: plugins/mergePaths.js [hunk 1]
```diff
@@ -10,6 +13,19 @@ import { path2js, js2path, intersects } from './_path.js';
...
+ * @param {XastElement} element
+ * @param {ComputedStyles} computedStyle
+ * @param {string} attName
+ */
+function elementHasURL(element, computedStyle, attName) {
+  const style = computedStyle[attName];
+  if (!style || style.type !== 'static') {
+    return false;
+  }
+  return style.value && style.value.includes('url(');
```
Comment (SethFalco) [inline plugins/mergePaths.js:26]: Perhaps this should be refactored to reuse the `includeUrlReference` utility?

Just helps to keep how we determine if something has a URL reference consistent. I'd also propose using `Url` instead of `URL` for consistency as well, for example when compared to our existing `includesUrlReference` function.

```suggestion
 * @param {ComputedStyles} computedStyle
 * @param {string} attName
 * @returns {boolean}
 */
function elementHasUrl(computedStyle, attName) {
  const style = computedStyle[attName];

  if (style?.type === 'static') {
    return includesUrlReference(style.value);
  }

  return false;
```

(This would also require changing other references to `elementHasURL`.)

**Review by SethFalco — COMMENTED** [review]
I've left one minor comment, but overall this looks good. Thanks for spotting the issue and submitting a patch.

**Review by SethFalco — APPROVED** [review]

**Comment by KTibow** [comment]
I'm a bit late here but this "is the path bounding box sensitive?" logic would be useful for #1951, and I'm going to move it to a function to reduce duplication. Which file would that function best fit in?

**Comment by SethFalco** [comment]
@KTibow Nothing shouts out to me, so I'd default to `lib/svgo/tools.js`.
