### PR TITLE
fix(cleanupIds): handle no-uri-encoded references

### LINKED ISSUE #1981: [cleanupIDs] symbol is incorrectly removed when its ID is *NOT* used by URL-encoded reference
**Describe the bug**

Last year's PR #1880 fixed the issue with URL encoding of IDs in `href` or `url()`. However, in practical use, we found that due to differences in SVG export tools or improper use, the SVG files delivered by designers to developers often have references to graphics, gradients, etc., in `url()` that are not necessarily URL-encoded.

Here is one of my actual examples (with business desensitization):

```svg
<svg xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="渐变_1" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="10%" stop-color="#c71700" />
      <stop offset="60%" stop-color="orange" />
      <stop offset="100%" stop-color="#5a2100" />
    </linearGradient>
  </defs>
  <rect x="30" y="30" height="150" width="370" fill="url(#渐变_1)" />
</svg>
```

After this SVG was processed by svgo, it became like this:
```svg
<svg xmlns="http://www.w3.org/2000/svg">
  <path fill="url(#渐变_1)" d="M30 30h370v150H30z"/>
</svg>
```

I traced the code and found that during the search for reference IDs, only URL-encoded IDs were used, which led to the unencoded IDs not being matched. As a result, in subsequent processing, they were considered as unreferenced, useless nodes and were deleted.

https://github.com/svg/svgo/blob/8d6385bd9ab49d1d300a10268930238baa5eb269/plugins/cleanupIds.js#L236

I will submit a PR shortly to fix this issue.

**Desktop (please complete the following information):**

- SVGO Version 3.2.0
- NodeJs Version 20.12.0
- OS: macOS

### PR DESCRIPTION
**Pull request by liuweifeng**
fixed #1981 .

### CODE REVIEW

File: plugins/cleanupIds.js [hunk 1]
```diff
@@ -233,7 +233,7 @@ export const fn = (_root, params) => {
                 if (value.includes('#')) {
                   // replace id in href and url()
                   element.attributes[name] = value.replace(
-                    `#${encodeURI(id)}`,
+                    new RegExp(`#(${id}|${encodeURI(id)})`),
                     `#${currentIdString}`,
                   );
```
Comment (SethFalco) [inline plugins/cleanupIds.js:238]: Something like this would be better:

```js
                  element.attributes[name] = value
                    .replace(`#${encodeURI(id)}`, `#${currentIdString}`)
                    .replace(`#${id}`, `#${currentIdString}`);
```

The proposed version opens us up to a potential ReDoS, as a user provides the SVG which we'd derive both the regex and value. A malicious user could upload a vulnerable SVG to a server that uses SVGO to abuse this.

Let's keep things simple and just chain two replaces. 👍🏽

File: test/plugins/cleanupIds.26.svg.txt [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+    <rect x="30" y="30" height="150" width="370" fill="url(#渐变_1)" />
+</svg>
+
+@@@
+
+<svg xmlns="http://www.w3.org/2000/svg">
+    <defs>
+        <linearGradient id="a" x1="0%" y1="0%" x2="100%" y2="0%">
+            <stop offset="10%" stop-color="#c71700"/>
+            <stop offset="60%" stop-color="orange"/>
```
Comment (SethFalco) [inline test/plugins/cleanupIds.26.svg.txt:24]:
```suggestion
            <stop offset="100%" stop-color="#5a2100" />
        </linearGradient>
    </defs>
    <rect x="30" y="30" height="150" width="370" fill="url(#渐变_1)" />
</svg>

@@@

<svg xmlns="http://www.w3.org/2000/svg">
    <defs>
        <linearGradient id="a" x1="0%" y1="0%" x2="100%" y2="0%">
            <stop offset="10%" stop-color="#c71700"/>
```

Just to keep the tests minimal, can we omit the two lines with offset 60%? We prefer for the tests to be as small as possible, so they just focus on what they're intended to test.

**Review by SethFalco — COMMENTED** [review]
I've left a comment as I believe there is a vulnerability in this version.

Overall, the issue and solution makes sense though. Thanks for submitting a patch!

File: plugins/cleanupIds.js (hunk 1 above)
Comment (liuweifeng) [reply plugins/cleanupIds.js]: Thank you for your review. It was indeed an oversight on my part, and I have already submitted the fix to the current PR.

Comment (SethFalco) [reply plugins/cleanupIds.js]: Thanks for addressing this.

Just leaving more context here, as I received an email asking about this vulnerability, and as it was never merged, I see no issue with demonstrating how to abuse it publically for anyone interested.

**pwned.svg**
```svg
<svg xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="(#+)+$" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="10%" stop-color="#c71700" />
    </linearGradient>
  </defs>
  <rect x="30" y="30" height="150" width="370" fill="############################X url('#(#+)+$')" />
</svg>
```

Then one way or another, a computer attempts to optimize this SVG. In CLI this would be with:

```sh
svgo pwned.svg -o out.svg
```

It would identify an element with an ID of `(#+)+$`, an evil regex, then match it to the value of `############################X url('#(#+)+$')` further down, with each additional `#` doubling the time it takes to process the SVG.

The above took 15 seconds on my computer (16 threads), so with just 7 more `#` symbols would take it to an hour to process.

**Review by SethFalco — APPROVED** [review]

**Comment by SethFalco** [comment]
Thanks for spotting the issue and submitting a patch! This will be released by the end of the month.
