### PR TITLE
fix(removeHiddenElems): handle defs better

### LINKED ISSUE #1851: Regression in 3.0.4: incorrectly removes reusable elements, but leaves references to it
**Describe the bug**
Combination of the following 3 plugins since version 3.0.4 incorrectly removes reusable element, resulting in broken icon:
```
'removeHiddenElems',
'convertPathData',
'reusePaths',
```

**To Reproduce**
Attempt to optimise the following icon using 3 plugins listed above:
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128">
	<path fill="#BD202E" d="M15.852 62.452Z"/>
	<path fill="#BD202E" d="M15.852 62.452Z" opacity=".35"/>
</svg>
```

**Expected behavior**
Expected icon that works: either empty (since paths are useless) or at least not broken.

**Actual behavior**
Actual result:
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128">
        <use href="#reuse-0"/>
        <use opacity=".35" href="#reuse-0"/>
    </svg>
```

Element with id `reuse-0` is missing.

**Desktop (please complete the following information):**
 - SVGO Version: 3.0.4
 - NodeJs Version: 20.5.0
 - OS: macOS 14.1.1
 
**Additional context**
In version 3.0.3 same code results in:
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128">
        <defs>
                <path fill="#BD202E" d="M15.852 62.452Z" id="reuse-0"/>
        </defs>
        <use href="#reuse-0"/>
        <use opacity=".35" href="#reuse-0"/>
    </svg>
```
Plugin `removeHiddenElems` fails in 3.0.3, but at least icon is not broken.

### PR DESCRIPTION
**Pull request by KTibow**
Relocate logic to run in node.exit instead of checking in svg's exit:
  - remove broken uses
  Changed from checking each use to making a list of uses, to fix #1851
  - remove unused defs
  Fixed a typo so it actually removes them, and add some safeguards
  - remove empty defs
  Changed from checking each def to making a list of defs

### CODE REVIEW

**Comment by KTibow** [comment]
Okay so turns out that the unused definitions logic was just always broken, so I'm having to fix the existing implementation

File: plugins/removeHiddenElems.js [hunk 1]
```diff
@@ -123,6 +135,32 @@ exports.fn = (root, params) => {
...
       enter: (node, parentNode) => {
+        if (
+          (node.name === 'style' && node.children.length !== 0) ||
+          hasScripts(node)
+        ) {
+          deoptimized = true;
+          return;
+        }
+
+        // Store uses so that they can be removed if broken
```
Comment (SethFalco) [inline plugins/removeHiddenElems.js:146]: Mind dropping the new comments?

Comments that just explain what the code is doing are redundant, this also applies to most of the other comments in the project.

The code is clear enough as it is. If it's really so complicated that it needs an explanation, it should be in its own function and get a JSDoc, or alternatively may need a refactor.

File: plugins/removeHiddenElems.js [hunk 2]
```diff
@@ -356,37 +394,35 @@ exports.fn = (root, params) => {
...
+              detachNodeFromParent(node, parentNode);
+            }
           }
-
-          return;
         }
 
-        if (node.name === 'svg' && parentNode.type === 'root') {
+        // Remove definitions that are unused
+        if (!deoptimized) {
```
Comment (SethFalco) [inline plugins/removeHiddenElems.js:412]: Could you provide an example/test where de-optimizing for styles makes sense?

(This section needs a refactor in general, we should be collecting the relevant data while visiting instead of CSS selecting at the end. I can handle this later, since it's out-of-scope for this PR, though.)

**Review by SethFalco — COMMENTED** [review]
Hey! Thanks for submitting a PR.

I've left a few comments, but the proposed fix makes sense. There are just a few issues with the implementation.

Can you please also add a test that reproduces the issue you're fixing.

File: plugins/removeHiddenElems.js [hunk 3]
```diff
@@ -123,6 +135,32 @@ exports.fn = (root, params) => {
...
+        ) {
+          deoptimized = true;
+          return;
+        }
+
+        // Store uses so that they can be removed if broken
+        // and used to determine if a definition is unused
+        if (node.name == 'use') {
+          const reference = Object.keys(node.attributes).find(
+            (attr) => attr === 'href' || attr.endsWith('href')
```
[the remark this answers is not in the document]
Comment (KTibow) [reply plugins/removeHiddenElems.js:150]: typo :sweat_smile:

File: plugins/removeHiddenElems.js (hunk 2 above)
Comment (KTibow) [reply plugins/removeHiddenElems.js:412]: Something like this
```xml
<svg>
  <defs>
    <linearGradient id="a">
      ...
    </linearGradient>
  </defs>
  <rect width="128" height="128></rect>
  <style> rect { fill: url(#a); } </style>
</svg>
```

Comment (SethFalco) [reply plugins/removeHiddenElems.js:412]: Make sense! I forgot definitions could be referenced from the style element.

I'd like if we could remove the exception on styles later, but this is fine for now. Later I can work on a PR to check the stylesheet for references to the ID as well.

**Comment by KTibow** [comment]
Now I'm running into the problem where it has a different behavior in multipass than singlepass, so it fails no matter what.
Context: in this
```xml
<svg xmlns="http://www.w3.org/2000/svg">
    <defs>
        <linearGradient id="a">
        </linearGradient>
    </defs>
</svg>
```
singlepass converts it to this, because the empty defs remover runs before the final pass
```xml
<svg xmlns="http://www.w3.org/2000/svg">
    <defs />
</svg>
```
but multipass converts it to this
```xml
<svg xmlns="http://www.w3.org/2000/svg" />
```

What's the most reasonable solution to this? Is there an elegant way to run the empty defs remover after the final pass?

**Comment by SethFalco** [comment]
> Is there an elegant way to run the empty defs remover after the final pass?

Perhaps the best approach would be to take from here:

https://github.com/svg/svgo/blob/3dc2f6fef7f67596eab64b0a98cfa68872e5609c/plugins/convertOneStopGradients.js#L36

So whenever we remove a node from a `<defs>`, store the effected `<defs`> node.
Then in `root` you can iterate these and check if they're empty there.

**Comment by KTibow** [comment]
While there's more to address I'm off to lunch, I'll fix this soon

File: plugins/removeHiddenElems.js [hunk 4]
```diff
@@ -74,6 +75,21 @@ exports.fn = (root, params) => {
    */
   const removedDefIds = new Set();
 
+  /**
+   * @type {Map<XastElement, XastParent>}
+   */
+  const allDefs = new Map();
+
+  /**
+   * @type {Map<string, Array<{node: XastElement, parentNode: XastParent }>>}
```
Comment (SethFalco) [inline plugins/removeHiddenElems.js:84]:
```suggestion
   * @type {Map<string, Array<{node: XastElement, parentNode: XastParent}>>}
```

```suggestion
   * @type {Map<string, Array<{ node: XastElement, parentNode: XastParent }>>}
```

Very petty, and not sure if the linter cares, but could we do one of these? ^-^'

File: plugins/removeHiddenElems.js [hunk 5]
```diff
@@ -350,46 +393,44 @@ exports.fn = (root, params) => {
...
-                attrValue.slice(attrValue.indexOf('#') + 1).trim()
-              )
-          );
-
-          if (referencesRemovedDef) {
-            detachNodeFromParent(node, parentNode);
+    },
+    root: {
+      exit: () => {
+        // Remove uses of deleted definitions
```
Comment (SethFalco) [inline plugins/removeHiddenElems.js:399]:
```suggestion
```

Sorry for not being explicit, could we remove these comments too?
The code is all very clear already.

File: plugins/removeHiddenElems.js [hunk 6]
```diff
@@ -350,46 +393,44 @@ exports.fn = (root, params) => {
...
+            for (const { node, parentNode } of refs) {
+              detachNodeFromParent(node, parentNode);
+            }
           }
-
-          return;
         }
 
-        if (node.name === 'svg' && parentNode.type === 'root') {
+        // Remove definitions that are unused
```
Comment (SethFalco) [inline plugins/removeHiddenElems.js:409]:
```suggestion
```

File: plugins/removeHiddenElems.js [hunk 7]
```diff
@@ -350,46 +393,44 @@ exports.fn = (root, params) => {
...
 
             const element = querySelector(root, selector);
             if (element == null) {
-              detachNodeFromParent(node, nonRenderedParent);
+              detachNodeFromParent(nonRenderedNode, nonRenderedParent);
             }
           }
         }
+
+        // Remove empty defs
```
Comment (SethFalco) [inline plugins/removeHiddenElems.js:428]:
```suggestion
```

**Review by SethFalco — COMMENTED** [review]
This looks good now! And thanks for resolving the other issues you found.
Just left a few _very petty_ notes, but happy to merge overall.

**Comment by SethFalco** [comment]
Great! Thanks for resolving the issue, and improving the plugin in general.
